name: demo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  face_camera: ^0.1.4
  cross_file: ^0.3.2
  image: ^4.5.4
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  http: ^0.13.6
  device_preview: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.0.15
  audioplayers: ^5.2.1
  animated_text_kit: ^4.2.2
  flutter_tts: ^3.8.4
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
  